In [3]:
import gym
import numpy as np

In [5]:
env = gym.make('FrozenLake-v0')

In [7]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [11]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.684


In [14]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  3.25834179e-01   1.65134646e-02   1.86838351e-02   1.51282262e-02]
 [  2.06702919e-03   2.60720140e-03   5.17872982e-04   3.00581297e-01]
 [  1.16889103e-01   5.36188118e-03   8.50128500e-03   3.65823042e-03]
 [  5.12329630e-04   2.98681446e-04   3.35252372e-04   2.20560771e-03]
 [  4.01317871e-01   3.49277041e-03   8.71664331e-03   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.01841126e-03   1.52158782e-04   2.05921512e-03   1.15274191e-05]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  5.37580179e-03   0.00000000e+00   1.15333513e-02   5.14400418e-01]
 [  0.00000000e+00   8.03768794e-01   6.67251647e-03   0.00000000e+00]
 [  7.37449488e-01   0.00000000e+00   0.00000000e+00   1.13688564e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   7.31043514e-01   0