In [17]:
import numpy as np
from numpy.linalg import inv

In [3]:
import tensorflow as tf

In [5]:
import matplotlib as plt

In [9]:
a = np.zeros((10,10))

print(a)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [12]:
b = np.ones((10,10))

print(b)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [22]:
c = np.eye(10)

print(c)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [24]:
print(c * b)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [26]:
randomarray = np.random.random((10,10))

print(randomarray)

inv(randomarray)

[[ 0.22978298  0.61527208  0.02356068  0.57505285  0.24028465  0.00809197
   0.6581292   0.44119153  0.28047396  0.05975378]
 [ 0.0919267   0.17212182  0.6453301   0.14850595  0.83092845  0.70276894
   0.58874203  0.85706743  0.14531019  0.06579125]
 [ 0.54472476  0.27480563  0.19286446  0.56325544  0.08806353  0.7672292
   0.5016974   0.36338899  0.44332913  0.95871939]
 [ 0.6099092   0.90692885  0.41951812  0.44094865  0.79832093  0.53203038
   0.81261209  0.38420077  0.73093042  0.0505989 ]
 [ 0.78340139  0.52785039  0.93663335  0.91320876  0.77870936  0.69036166
   0.92508902  0.49884479  0.07688362  0.08534985]
 [ 0.04132423  0.89897474  0.31931364  0.25508207  0.6865935   0.95423377
   0.48587238  0.81856995  0.51014998  0.27489147]
 [ 0.7256467   0.82215627  0.77983745  0.99468929  0.43191563  0.65927093
   0.11613337  0.77209681  0.39033112  0.77780168]
 [ 0.35172002  0.59474885  0.88315103  0.83815676  0.20577     0.80136921
   0.09457142  0.12215057  0.93796728  0.62116889]
 

array([[ -1.17153674e+00,  -5.59850668e-01,   7.00391181e-02,
          7.53190730e-01,   2.13779916e-01,  -2.28380675e-01,
          7.80862493e-01,  -6.28682764e-01,   9.53464096e-01,
         -8.15536724e-01],
       [  1.80289300e+00,  -7.47213411e-01,  -1.34618490e+00,
         -1.33118458e+00,  -1.17321026e+00,   1.26545713e+00,
         -1.70675744e-01,  -4.50262944e-01,   1.71367101e+00,
          1.40354835e+00],
       [  2.67465951e+00,   1.02260421e+00,  -1.92999774e+00,
         -2.39695881e+00,  -2.04828910e+00,  -4.06656680e-03,
         -5.62071108e-01,   3.40238623e-01,   3.00712178e+00,
          1.77771254e+00],
       [ -1.84872661e+00,  -6.97268956e-01,   1.34991937e+00,
          1.45778928e+00,   2.66650454e+00,  -4.80250558e-01,
          5.10745785e-01,   6.77623183e-01,  -3.27320252e+00,
         -1.59341571e+00],
       [ -2.55459004e+00,   5.12478667e-01,   1.50039865e+00,
          3.35075983e+00,   1.31377917e+00,  -1.38369557e+00,
          7.71547093e-01